import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import SearchPage from '../components/SearchPage'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'
import BlurNav from '@/components/BlurNav'


export default function Home() {
  return (
    <>
      <Head>
        <title>Space Universe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BlurNav/>
      <main className={styles.main} >
          <Navbar/>
          <Hero/>
          <SearchPage/>
          <Footer/>
      </main>
    </>
  )
}
